### ISSUE TITLE
Development finished?

### ISSUE THREAD

**Issue by Hovestar** [tfonrouge/hbmongoc#6]
We were looking at using this, but I can't tell if its in a working state or not. Was this left in a state where it is usable or is it still in progress?

**Comment by tfonrouge** [comment]
It is usable in their current state. I'm using it to store/retrieve data from a real time manufacturing machine array (thousands of docs per day).

The current implemented functions are showed in the hbmongoc.hbx project file.

Check the tests/samples and see how it works for you.

**Comment by Hovestar** [comment]
Perfect. We're getting a compiler warning about duplicate declarations right now, but I wanted to make sure I wasn't barking up the wrong tree.
